path: C:\Users\15795\Desktop

rep_columns:
  jd_BT_limitAmt: [-1]
  jd_JT_limitAmt: [-1]
  jd_BT_timeDiff: [0.]
  jd_JT_timeDiff: [0.]


num_columns: [
  jd_if_houseRepay,
  jd_houseRepay_cnt_12m,
  jd_houseRepay_avgAmt_12m,
  jd_if_default,
  jd_default_cnt_12m,
  jd_default_cnt_3m,
  jd_default_maxCumulativeCnt_12m,
  jd_BT_limitAmt,
  jd_BT_timediff,
  jd_JT_limitAmt,
  jd_JT_timediff,
  jd_BTloan_cnt_12m,
  jd_BTloan_cnt_3m,
  jd_BTloan_amt_12m,
  jd_BTloan_amt_3m,
  jd_BTloan_cntGR_6m,
  jd_BTloan_cntGR_3m,
  jd_BTloan_amtGR_6m,
  jd_BTloan_amtGR_3m,
  jd_loan_cnt_12m,
  jd_loan_cnt_3m,
  jd_loan_amt_12m,
  jd_loan_amt_3m,
  jd_loan_cntGR_6m,
  jd_loan_cntGR_3m,
  jd_loan_amtGR_6m,
  jd_loan_amtGR_3m,
  jd_BTquick_cnt_12m,
  jd_BTquick_cnt_3m,
  jd_BTquick_amt_12m,
  jd_BTquick_amt_3m,
  jd_BillInstallment_cnt_12m,
  jd_BillInstallment_cnt_3m,
  jd_BillInstallment_amt_12m,
  jd_BillInstallment_amt_3m,
  jd_BillInstallment_minAmt_12m,
  jd_BillInstallment_minAmt_3m,
  jd_BillInstallment_cntGR_6m,
  jd_BillInstallment_cntGR_3m,
  jd_BillInstallment_amtGR_6m,
  jd_BillInstallment_amtGR_3m,
  jd_BTcash_cnt_12m,
  jd_BTcash_cnt_3m,
  jd_BTcash_amt_12m,
  jd_BTcash_amt_3m,
  jd_repay_cnt_12m,
  jd_repay_cnt_3m,
  jd_repay_amt_12m,
  jd_repay_amt_3m,
  jd_monRepay_maxAmt_12m,
  jd_monRepay_maxAmt_3m,
  jd_autoRepayFail_cnt_12m,
  jd_autoRepayFail_cnt_3m,
  jd_autoRepayFail_amt_12m,
  jd_autoRepayFail_amt_3m,
  jd_shopRepay_cnt_12m,
  jd_shopRepay_cnt_3m,
  jd_shopRepay_amt_12m,
  jd_shopRepay_amt_3m,
  jd_shopDefault_cnt_12m,
  jd_shopDefault_cnt_3m,
  jd_shopDefault_amt_12m,
  jd_shopDefault_amt_3m,
]

cat_columns: [
]






















