path: C:\Users\P1352\Desktop

dataset:
  tra: train.csv
  tes: test.csv

columns:
  keep: [姓名, 手机号, 身份证号, backdate]
  drop: []
  date: backdate
  target: target

feature gen:
  add:
  sub:
  mul:
  div:
  stats:
  concat:

feature dis:
  cat cols: [
    风险等级
  ]
  num cols: [
    score,
    30天内多头次数,
    60天内多头次数,
    90天内多头次数,
    180天多头次数,
    240天多头次数,
    30天多头机构数,
    60天多头机构数,
    90天多头机构数,
    180天多头机构数,
    240天多头机构数,
    30天P2P多头次数,
    30天现金贷多头次数,
    30天其他机构多头次数,
    60天P2P多头次数,
    60天现金贷多头次数,
    60天其他机构多头次数,
    90天P2P多头次数,
    90天内消费分期多头次数,
    90天内现金贷多头次数,
    90天内其他机构多头次数,
    180天P2P多头次数,
    180天消费分期多头次数,
    180天现金贷多头次数,
    180天其他机构多头次数,
    240天P2P多头次数,
    240天消费分期多头次数,
    240天现金贷多头次数,
    240天其他机构类型多头次数,
    信用分,
    还款意愿,
  ]

feature sel:


